# Generated by tools/packaging/render-package-manifests.mjs. Do not edit by hand.
class Sharplsp < Formula
  desc "Open-source .NET language server with C# and F# intelligence"
  homepage "https://github.com/Nimblesite/SharpLsp"
  version "0.23.0"
  license "MIT"

  on_macos do
    # No darwin-x64 archive is published — that build hangs on GitHub's hosted
    # macos-13 runners, so its matrix entry is commented out in release.yml.
    # Declaring the requirement gives Intel Macs a clear architecture error
    # instead of a 404 mid-download.
    depends_on arch: :arm64
    url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.23.0/sharplsp-darwin-arm64.tar.gz"
    sha256 "4d8db8fe97cff12fcd52fcd6fd78b64ee627d30bc97bfe37d8444c8677c6ab5f"
  end

  on_linux do
    on_arm do
      url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.23.0/sharplsp-linux-arm64.tar.gz"
      sha256 "ce2a23a7e5ad541d0f3081652ee6cf64d6a63ce4d0bd48175a16a28be0034f90"
    end
    on_intel do
      url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.23.0/sharplsp-linux-x64.tar.gz"
      sha256 "6b28fec6fa62ab1caeef167c01909dc1e1f2ad720589e5f97581ea7829a268ce"
    end
  end

  # The archive is not a bare binary: `sharplsp` spawns a Roslyn sidecar and an
  # FCS sidecar, and finds them RELATIVE TO ITSELF. `lib/sharplsp/` is the
  # `<exe_dir>/../lib/sharplsp/<subdir>/` layout the host already looks in, so
  # installing them here needs no wrapper script and no environment variable.
  # Installing only the binary would produce a language server that starts and
  # then answers nothing.
  def install
    bin.install "sharplsp"
    (lib/"sharplsp").install "sidecar-csharp", "sidecar-fsharp"
  end

  # Deliberately no `depends_on "dotnet"`: the sidecars target net10.0 and the
  # Homebrew dotnet formula is not pinned to that. Say so instead of installing
  # a runtime that cannot load them.
  def caveats
    <<~EOS
      SharpLsp needs the .NET 10 SDK on PATH.
      The C# and F# sidecars are framework-dependent, and only the VS Code
      extension acquires the SDK for you.
    EOS
  end

  test do
    assert_match "sharplsp #{version}", shell_output("#{bin}/sharplsp --version")
  end
end
