# Generated by tools/packaging/render-package-manifests.mjs. Do not edit by hand.
class Sharplsp < Formula
  desc "Open-source .NET language server with C# and F# intelligence"
  homepage "https://github.com/Nimblesite/SharpLsp"
  version "0.21.0"
  license "MIT"

  on_macos do
    # No darwin-x64 archive is published — that build hangs on GitHub's hosted
    # macos-13 runners, so its matrix entry is commented out in release.yml.
    # Declaring the requirement gives Intel Macs a clear architecture error
    # instead of a 404 mid-download.
    depends_on arch: :arm64
    url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.21.0/sharplsp-darwin-arm64.tar.gz"
    sha256 "fa59ab5ed89cf822a1373d98ef90ddb8ce8409ac971ebaaf24dc88313ecc2e72"
  end

  on_linux do
    on_arm do
      url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.21.0/sharplsp-linux-arm64.tar.gz"
      sha256 "ab7a61ed41fb12de370287a08f267b46d0f611ff69df7345ca295c429d763b5f"
    end
    on_intel do
      url "https://github.com/Nimblesite/SharpLsp/releases/download/v0.21.0/sharplsp-linux-x64.tar.gz"
      sha256 "10cd5b22bd828b895831d0596c18238246bfca1a70be3806e49f11bfa0ebc26a"
    end
  end

  # The archive is not a bare binary: `sharplsp` spawns a Roslyn sidecar and an
  # FCS sidecar, and finds them RELATIVE TO ITSELF. `lib/sharplsp/` is the
  # `<exe_dir>/../lib/sharplsp/<subdir>/` layout the host already looks in, so
  # installing them here needs no wrapper script and no environment variable.
  # Installing only the binary would produce a language server that starts and
  # then answers nothing.
  def install
    bin.install "sharplsp"
    (lib/"sharplsp").install "sidecar-csharp", "sidecar-fsharp"
  end

  # Deliberately no `depends_on "dotnet"`: the sidecars target net10.0 and the
  # Homebrew dotnet formula is not pinned to that. Say so instead of installing
  # a runtime that cannot load them.
  def caveats
    <<~EOS
      SharpLsp needs the .NET 10 SDK on PATH.
      The C# and F# sidecars are framework-dependent, and only the VS Code
      extension acquires the SDK for you.
    EOS
  end

  test do
    assert_match "sharplsp #{version}", shell_output("#{bin}/sharplsp --version")
  end
end
